## How to find missing number in a given integer array of 1 to 100

In [2]:
import random
import array
import numpy as np


In [3]:
test_array = np.linspace(1,100, num = 100, dtype=int)

In [4]:
test_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
test_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [6]:

removed_item = np.random.choice(test_array, size= len(test_array)-1, replace = False)


In [7]:
removed_item

array([ 63,  93,  76,  94,  16,  69,  39,  60,   7,  38,  68,   5,  19,
        44,  52,  92,  99,  25,  31,  43,  81,  20,  74,   3,  88,  42,
        75,   4,  95,  30,  29,  87,  49,  96,  89,  56, 100,  66,  27,
        67,  79,  65,  82,  14,  86,  18,  85,  62,  33,  32,  77,  11,
        10,  57,  35,  15,  45,  70,  37,  98,   1,  26,  54,  22,  17,
        28,  51,  59,  12,  48,  47,  46,  40,  84,   8,  24,  97,  71,
        83,  58,  72,  73,  91,  34,  78,  50,  90,  21,   9,  13,  80,
        64,  23,   2,  41,   6,  36,  55,  53])

In [8]:
removed_item.sort()

In [9]:
removed_item

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
for i in range(1,len(removed_item)):
    if i == removed_item[i-1]:
        pass
    else:
        print (i, "is missing")
        break
        

61 is missing


In [11]:
test_array_sum = test_array.sum()
removed_item_sum = removed_item.sum()

In [12]:
test_array_sum - removed_item_sum

61

### How to find and remove Duplicate Numbers on a given integer array.

In [13]:
test_array_dup = np.array(np.random.choice(test_array, 100))

In [14]:
len(test_array_dup)

100

In [15]:
len(set(test_array_dup))


61

In [16]:
seen = set()
dup = set()
for i in (test_array_dup):
    if i in seen:
        dup.add(i)
    else:
        seen.add(i)
        

In [17]:
dup

{6,
 8,
 11,
 14,
 15,
 16,
 20,
 22,
 24,
 25,
 28,
 31,
 33,
 35,
 36,
 37,
 38,
 44,
 46,
 59,
 70,
 71,
 75,
 79,
 82,
 85,
 87,
 100}

### How do you find the largest and smallest number in an unsorted integer array?

In [18]:
high = test_array_dup[0]
low = test_array_dup[0]
for i in test_array_dup:
    if i > low and i < high:
        pass
    elif  high < i:
        high = i
    elif low > i:
        low = i

print (high, "is the largest,", low, "is the lowest.")   


100 is the largest, 5 is the lowest.


In [19]:
test_array_dup.min()

5

In [20]:
test_array_dup.max()

100

### How do you find all pairs of an integer array whose sum is equal to a given number?

In [21]:
random_number = random.randint(50, 200)

In [22]:
random_number

60

In [23]:
counter = 0
equality = []
achieved_list = []
for i in range(len(test_array_dup)):
    if test_array_dup[i] > random_number:
        pass
    else:
        for j in range(i+1, len(test_array_dup)):
            if test_array_dup[j] > random_number:
                pass
            else:
                if test_array_dup[i]+test_array_dup[j] == random_number:
                    equality.append([test_array_dup[i],test_array_dup[j], i, j])


In [24]:
equality

[[20, 40, 0, 8],
 [44, 16, 1, 16],
 [44, 16, 1, 71],
 [44, 16, 1, 75],
 [33, 27, 5, 22],
 [11, 49, 6, 26],
 [40, 20, 8, 18],
 [25, 35, 9, 15],
 [25, 35, 9, 88],
 [25, 35, 11, 15],
 [25, 35, 11, 88],
 [55, 5, 12, 43],
 [15, 45, 13, 99],
 [35, 25, 15, 28],
 [35, 25, 15, 91],
 [16, 44, 16, 19],
 [16, 44, 16, 30],
 [44, 16, 19, 71],
 [44, 16, 19, 75],
 [36, 24, 21, 45],
 [36, 24, 21, 80],
 [27, 33, 22, 83],
 [27, 33, 22, 92],
 [22, 38, 25, 64],
 [22, 38, 25, 72],
 [49, 11, 26, 51],
 [25, 35, 28, 88],
 [44, 16, 30, 71],
 [44, 16, 30, 75],
 [46, 14, 34, 61],
 [46, 14, 34, 95],
 [24, 36, 45, 48],
 [36, 24, 48, 80],
 [22, 38, 53, 64],
 [22, 38, 53, 72],
 [43, 17, 56, 97],
 [14, 46, 61, 90],
 [6, 54, 62, 78],
 [38, 22, 64, 68],
 [6, 54, 65, 78],
 [22, 38, 68, 72],
 [15, 45, 82, 99],
 [35, 25, 88, 91],
 [46, 14, 90, 95]]

### How is an integer array sorted in place using the quicksort algorithm? 

A random pivot is used. That pivot is a number occupying a slot in the array. Ideally its near the middle, but that is not too important. The algorithm will scan both sides of the array to ensure that the numbers on the left are less than the pivot number the ones on the right are greater. If they are not, they are swapped. This continues with a new pivot everytime.

In [25]:
qs_array = [6,5,3,1,8,7,2,4]


In [26]:
pivot = random.choice(qs_array)

In [27]:
pivot

8

In [28]:
#comparision of the sides.
left_array = qs_array
for left

SyntaxError: invalid syntax (<ipython-input-28-99d631f2aec2>, line 3)

### How do you remove duplicates from an array in place? 

In [ ]:
test_array_ip = test_array_dup

In [ ]:
seen_set = set()
removal_list = []
for i in range(len(test_array_ip)):
    if test_array_ip[i] not in seen_set:
        seen_set.add(test_array_ip[i])
    else:
        removal_list.append(i)

In [ ]:
test_array_ip = np.delete(test_array_ip, removal_list)

In [ ]:
len(test_array_ip)

### How do you reverse an array in place in Java? 


In [ ]:
def swap(array, x,y):
    array[x],array[y] = array[y],array[x]
    return array

In [ ]:
test_array_reversal = test_array_dup

In [ ]:
#length that we plan to use
array_length = int(len(test_array_reversal)/2)

In [ ]:
array_length

In [ ]:
for i in range(array_length):
    swap(test_array_reversal, i, -i-1)

In [ ]:
test_ar