## How to find missing number in a given integer array of 1 to 100

In [1]:
import random
import array
import numpy as np


In [2]:
test_array = np.linspace(1,100, num = 100, dtype=int)

In [3]:
test_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
test_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:

removed_item = np.random.choice(test_array, size= len(test_array)-1, replace = False)


In [6]:
removed_item

array([ 42,  31,  25,  18,  87,  24,  43,  93,  95,  48,  68,  64,  99,
        62,  66,  41,  53,   3,  79,  74,  78,  54,  81,  50,  39,  37,
        15,  72,  20,  88,  90,  73,   6,  21,  40,  11,  13, 100,  61,
        84,   8,  51,   4,  49,  57,  67,   2,  16,  22,  28,   1,  30,
        94,  26,   5,  71,  82,   9,  45,  58,  46,  91,  19,  44,  92,
        80,  52,  32,  76,  60,  77,  35,  29,  14,  85,  69,  96,  86,
        97,  65,  75,  23,  55,  47,  27,  56,  17,   7,  33,  70,  10,
        12,  34,  36,  59,  83,  98,  63,  38])

In [7]:
removed_item.sort()

In [8]:
removed_item

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
for i in range(1,len(removed_item)):
    if i == removed_item[i-1]:
        pass
    else:
        print (i, "is missing")
        break
        

89 is missing


In [10]:
test_array_sum = test_array.sum()
removed_item_sum = removed_item.sum()

In [11]:
test_array_sum - removed_item_sum

89

### How to find and remove Duplicate Numbers on a given integer array.

In [12]:
test_array_dup = np.array(np.random.choice(test_array, 100))

In [13]:
len(test_array_dup)

100

In [14]:
len(set(test_array_dup))


60

In [15]:
seen = set()
dup = set()
for i in (test_array_dup):
    if i in seen:
        dup.add(i)
    else:
        seen.add(i)
        

In [16]:
dup

{4,
 7,
 8,
 11,
 20,
 22,
 39,
 43,
 45,
 47,
 53,
 55,
 64,
 69,
 71,
 72,
 73,
 74,
 75,
 77,
 80,
 81,
 93,
 94,
 95,
 96,
 99}

### How do you find the largest and smallest number in an unsorted integer array?

In [17]:
high = test_array_dup[0]
low = test_array_dup[0]
for i in test_array_dup:
    if i > low and i < high:
        pass
    elif  high < i:
        high = i
    elif low > i:
        low = i

print (high, "is the largest,", low, "is the lowest.")   


99 is the largest, 2 is the lowest.


In [18]:
test_array_dup.min()

2

In [19]:
test_array_dup.max()

99

### How do you find all pairs of an integer array whose sum is equal to a given number?

In [20]:
random_number = random.randint(50, 200)

In [21]:
random_number

132

In [22]:
counter = 0
equality = []
achieved_list = []
for i in range(len(test_array_dup)):
    if test_array_dup[i] > random_number:
        pass
    else:
        for j in range(i+1, len(test_array_dup)):
            if test_array_dup[j] > random_number:
                pass
            else:
                if test_array_dup[i]+test_array_dup[j] == random_number:
                    equality.append([test_array_dup[i],test_array_dup[j], i, j])


In [23]:
equality

[[58, 74, 2, 18],
 [58, 74, 2, 32],
 [93, 39, 9, 11],
 [93, 39, 9, 49],
 [39, 93, 11, 22],
 [39, 93, 11, 26],
 [39, 93, 11, 82],
 [55, 77, 12, 30],
 [55, 77, 12, 77],
 [81, 51, 16, 92],
 [85, 47, 17, 67],
 [85, 47, 17, 85],
 [94, 38, 20, 53],
 [93, 39, 22, 49],
 [89, 43, 23, 34],
 [89, 43, 23, 44],
 [89, 43, 23, 81],
 [94, 38, 24, 53],
 [72, 60, 25, 65],
 [93, 39, 26, 49],
 [72, 60, 27, 65],
 [75, 57, 29, 50],
 [77, 55, 30, 54],
 [33, 99, 37, 43],
 [33, 99, 37, 98],
 [94, 38, 40, 53],
 [36, 96, 41, 45],
 [36, 96, 41, 88],
 [36, 96, 41, 93],
 [34, 98, 46, 89],
 [39, 93, 49, 82],
 [57, 75, 50, 61],
 [57, 75, 50, 95],
 [55, 77, 54, 77],
 [44, 88, 57, 74],
 [53, 79, 59, 60],
 [79, 53, 60, 75],
 [79, 53, 60, 96],
 [81, 51, 73, 92]]

### How is an integer array sorted in place using the quicksort algorithm? 

A random pivot is used. That pivot is a number occupying a slot in the array. Ideally its near the middle, but that is not too important. The algorithm will scan both sides of the array to ensure that the numbers on the left are less than the pivot number the ones on the right are greater. If they are not, they are swapped. This continues with a new pivot everytime.

In [227]:
qs_array = [6,5,3,1,8,7,2,4]


In [229]:
pivot = random.choice(qs_array)

In [230]:
pivot

7

In [ ]:
#comparision of the sides.
left_array = qs_array
for left

### How do you remove duplicates from an array in place? 

In [25]:
test_array_ip = test_array_dup

In [40]:
seen_set = set()
removal_list = []
for i in range(len(test_array_ip)):
    if test_array_ip[i] not in seen_set:
        seen_set.add(test_array_ip[i])
    else:
        removal_list.append(i)

95 set()
73 {95}
58 {73, 95}
7 {73, 58, 95}
22 {73, 58, 7, 95}
64 {7, 73, 22, 58, 95}
80 {64, 7, 73, 22, 58, 95}
92 {64, 7, 73, 80, 22, 58, 95}
93 {64, 7, 73, 80, 22, 58, 92, 95}
45 {64, 7, 73, 80, 22, 58, 92, 93, 95}
39 {64, 7, 73, 45, 80, 22, 58, 92, 93, 95}
55 {64, 7, 39, 73, 45, 80, 22, 58, 92, 93, 95}
21 {64, 7, 39, 73, 45, 80, 22, 55, 58, 92, 93, 95}
48 {64, 7, 39, 73, 45, 80, 21, 22, 55, 58, 92, 93, 95}
12 {64, 7, 39, 73, 45, 80, 48, 21, 22, 55, 58, 92, 93, 95}
81 {64, 7, 39, 73, 12, 45, 80, 48, 21, 22, 55, 58, 92, 93, 95}
85 {64, 7, 39, 73, 12, 45, 80, 48, 81, 21, 22, 55, 58, 92, 93, 95}
74 {64, 7, 39, 73, 12, 45, 80, 48, 81, 21, 22, 55, 85, 58, 92, 93, 95}
94 {64, 7, 39, 73, 74, 12, 45, 80, 48, 81, 21, 22, 55, 85, 58, 92, 93, 95}
20 {64, 7, 39, 73, 74, 12, 45, 80, 48, 81, 21, 22, 55, 85, 58, 92, 93, 94, 95}
89 {64, 7, 39, 73, 74, 12, 45, 80, 48, 81, 20, 21, 22, 55, 85, 58, 92, 93, 94, 95}
72 {7, 12, 20, 21, 22, 39, 45, 48, 55, 58, 64, 73, 74, 80, 81, 85, 89, 92, 93, 94, 95}
91

TypeError: delete() got an unexpected keyword argument 'inplace'

In [43]:
test_array_ip = np.delete(test_array_ip, removal_list)

In [45]:
len(test_array_ip)

60

### How do you reverse an array in place in Java? 


In [55]:
def swap(array, x,y):
    array[x],array[y] = array[y],array[x]
    return array

In [47]:
test_array_reversal = test_array_dup

In [60]:
#length that we plan to use
array_length = int(len(test_array_reversal)/2)

In [58]:
array_length

50.0

In [61]:
for i in range(array_length):
    swap(test_array_reversal, i, -i-1)

In [56]:
test_ar

array([73, 95, 58, 95,  7, 22, 64, 80, 92, 93, 45, 39, 55, 21, 48, 12, 81,
       85, 74,  7, 94, 20, 93, 89, 94, 72, 93, 72, 91, 75, 77, 64, 74,  8,
       43, 32, 22, 33, 20, 64, 94, 36, 11, 99, 43, 96, 34, 14, 54, 39, 57,
        7, 45, 38, 55, 69,  6, 44,  7, 53, 79, 75, 71,  2, 82, 60,  8, 47,
       11, 71, 71,  3, 73, 81, 88, 53, 30, 77, 35, 28,  7, 43, 93, 45,  4,
       47, 69, 83, 96, 98, 13, 86, 51, 96,  4, 75, 53, 80, 99, 19])

array([95, 73, 58, 95,  7, 22, 64, 80, 92, 93, 45, 39, 55, 21, 48, 12, 81,
       85, 74,  7, 94, 20, 93, 89, 94, 72, 93, 72, 91, 75, 77, 64, 74,  8,
       43, 32, 22, 33, 20, 64, 94, 36, 11, 99, 43, 96, 34, 14, 54, 39, 57,
        7, 45, 38, 55, 69,  6, 44,  7, 53, 79, 75, 71,  2, 82, 60,  8, 47,
       11, 71, 71,  3, 73, 81, 88, 53, 30, 77, 35, 28,  7, 43, 93, 45,  4,
       47, 69, 83, 96, 98, 13, 86, 51, 96,  4, 75, 53, 80, 99, 19])