## How to find missing number in a given integer array of 1 to 100

In [74]:
import random
import array
import numpy as np


In [88]:
test_array = np.linspace(1,100, num = 100, dtype=int)

In [89]:
test_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [90]:
test_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [91]:

removed_item = np.random.choice(test_array, size= len(test_array)-1, replace = False)


In [92]:
removed_item

array([ 21,  49,  27,  42,   1,  73,  74,  86,  82,  75,  46,  83,  96,
        52,  51,  16,  24,  94,  65,  93,  10,  50,  47,  32,  37,  18,
        90,  53,   6,  43,  84,   8,  70,   9,  61,  99,  87,  11,  58,
        89,  15,  41,   4,  77,  35,  63,  79,  85,  62, 100,  17,  97,
        95,  19,  81,   3,  48,  45,  39,  34,   7,  78,  59,  55,  31,
        91,  13,  98,  40,  69,  80,   5,  64,  28,  23,  60,  30,  36,
        14,  29,   2,  68,  76,  72,  88,  12,  26,  38,  92,  20,  22,
        25,  56,  54,  57,  33,  44,  67,  71])

In [96]:
removed_item.sort()

In [117]:
removed_item

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [125]:
for i in range(1,len(removed_item)):
    if i == removed_item[i-1]:
        pass
    else:
        print (i, "is missing")
        break
        

66 is missing


In [135]:
test_array_sum = test_array.sum()
removed_item_sum = removed_item.sum()

In [136]:
test_array_sum - removed_item_sum

66

### How to find and remove Duplicate Numbers on a given integer array.

In [142]:
test_array_dup = np.array(np.random.choice(test_array, 100))

In [161]:
len(test_array_dup)

100

In [160]:
len(set(test_array_dup))


67

In [175]:
seen = set()
dup = set()
for i in (test_array_dup):
    if i in seen:
        dup.add(i)
    else:
        seen.add(i)
        

In [179]:
dup

{4,
 7,
 8,
 9,
 14,
 16,
 18,
 19,
 32,
 34,
 37,
 38,
 49,
 50,
 54,
 62,
 70,
 71,
 77,
 81,
 86,
 95}

### How do you find the largest and smallest number in an unsorted integer array?

In [198]:
high = test_array_dup[0]
low = test_array_dup[0]
for i in test_array_dup:
    if i > low and i < high:
        pass
    elif  high < i:
        high = i
    elif low > i:
        low = i

print (high, "is the largest,", low, "is the lowest.")   


100 is the largest, 2 is the lowest.


In [199]:
test_array_dup.min()

2

In [200]:
test_array_dup.max()

100

### How do you find all pairs of an integer array whose sum is equal to a given number?

In [201]:
random_number = random.randint(50, 200)

In [202]:
random_number

85

In [218]:
counter = 0
equality = []
achieved_list = []
for i in range(len(test_array_dup)):
    if test_array_dup[i] > random_number:
        pass
    else:
        for j in range(i+1, len(test_array_dup)):
            if test_array_dup[j] > random_number:
                pass
            else:
                if test_array_dup[i]+test_array_dup[j] == random_number:
                    equality.append([test_array_dup[i],test_array_dup[j], i, j])


In [219]:
equality

[[14, 71, 0, 31],
 [14, 71, 0, 45],
 [53, 32, 2, 65],
 [53, 32, 2, 81],
 [53, 32, 2, 87],
 [53, 32, 2, 90],
 [82, 3, 3, 22],
 [33, 52, 4, 99],
 [16, 69, 5, 26],
 [77, 8, 6, 18],
 [77, 8, 6, 55],
 [77, 8, 6, 84],
 [68, 17, 7, 88],
 [11, 74, 9, 82],
 [56, 29, 10, 16],
 [51, 34, 11, 33],
 [51, 34, 11, 56],
 [38, 47, 12, 78],
 [16, 69, 13, 26],
 [81, 4, 14, 20],
 [81, 4, 14, 71],
 [19, 66, 15, 28],
 [8, 77, 18, 41],
 [4, 81, 20, 77],
 [50, 35, 21, 29],
 [69, 16, 26, 58],
 [66, 19, 28, 30],
 [35, 50, 29, 73],
 [71, 14, 31, 68],
 [71, 14, 31, 94],
 [60, 25, 36, 80],
 [63, 22, 37, 38],
 [12, 73, 39, 67],
 [37, 48, 40, 52],
 [77, 8, 41, 55],
 [77, 8, 41, 84],
 [70, 15, 42, 96],
 [38, 47, 43, 78],
 [71, 14, 45, 68],
 [71, 14, 45, 94],
 [13, 72, 51, 69],
 [48, 37, 52, 61],
 [70, 15, 53, 96],
 [70, 15, 62, 96],
 [4, 81, 71, 77],
 [70, 15, 95, 96]]

### How is an integer array sorted in place using the quicksort algorithm? 

A random pivot is used. That pivot is a number occupying a slot in the array. Ideally its near the middle, but that is not too important. The algorithm will scan both sides of the array to ensure that the numbers on the left are less than the pivot number the ones on the right are greater. If they are not, they are swapped. This continues with a new pivot everytime.

In [227]:
qs_array = [6,5,3,1,8,7,2,4]


In [229]:
pivot = random.choice(qs_array)

In [230]:
pivot

7

In [ ]:
#comparision of the sides.
left_array = qs_array
for left